name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .    # React app
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run front-end tests
        run: npm test

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend  # PHP backend folder
    env:
      DB_HOST: 127.0.0.1
      DB_NAME: reactsecure
      DB_USER: reactuser
      DB_PASS: StrongPass123!
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: reactsecure
          MYSQL_USER: reactuser
          MYSQL_PASSWORD: StrongPass123!

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo_mysql

      - name: Install MySQL client
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y default-mysql-client

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            mysql -h127.0.0.1 -uroot -prootpassword -e "SELECT 1" && break
            echo "Waiting for MySQL… ($i)"
            sleep 2
          done

      - name: Start PHP built-in server
        run: php -S 127.0.0.1:8000 -t . &

      - name: Wait for PHP endpoint
        run: |
          for i in {1..20}; do
            curl --silent --fail http://127.0.0.1:8000/register.php && break
            echo "Waiting for PHP… ($i)"
            sleep 2
          done

      - name: Run backend tests
        run: bash test-backend.sh
