  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    env:
      DB_HOST: 127.0.0.1      # ← override to localhost in Actions
      DB_NAME: reactsecure
      DB_USER: reactuser
      DB_PASS: StrongPass123!
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: reactsecure
          MYSQL_USER: reactuser
          MYSQL_PASSWORD: StrongPass123!
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo_mysql
      - name: Start PHP built-in server
        run: php -S 127.0.0.1:8000 -t . &
      - name: Wait for PHP+MySQL
        run: |
          for i in {1..20}; do
            curl --silent --fail http://127.0.0.1:8000/register.php && break
            echo "Waiting for PHP server… ($i)"
            sleep 2
          done
      - name: Run backend tests
        run: bash test-backend.sh
