   backend:
     runs-on: ubuntu-latest
     defaults:
       run:
         working-directory: ./backend
     services:
       mysql:
         image: mysql:8.0
         env:
           MYSQL_ROOT_PASSWORD: rootpassword
           MYSQL_DATABASE: reactsecure
           MYSQL_USER: reactuser
           MYSQL_PASSWORD: StrongPass123!
         options: >-
           --health-cmd="mysqladmin ping --silent"
           --health-interval=10s
           --health-timeout=5s
           --health-retries=3
     steps:
       - uses: actions/checkout@v3

+      - name: Install MySQL client
+        run: sudo apt-get update && sudo apt-get install -y default-mysql-client

       - name: Wait for MySQL
         run: |
           for i in {1..10}; do
             mysqladmin ping -h127.0.0.1 -uroot -prootpassword --silent && break
             echo "Waiting for MySQL… ($i)"
             sleep 2
           done

       - name: Run backend tests
         run: bash test-backend.sh
