name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .     # your React app lives at repo root
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install front-end dependencies
        run: npm ci

      - name: Run front-end tests
        run: npm test

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend  # your PHP backend folder
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: reactsecure
          MYSQL_USER: reactuser
          MYSQL_PASSWORD: StrongPass123!
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            mysqladmin ping -h127.0.0.1 -uroot -prootpassword --silent && break
            echo "Waiting for MySQL… ($i)"
            sleep 2
          done

      - name: Run backend API tests
        run: bash test-backend.sh
