name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .    # React app at repo root
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run front-end tests
        run: npm test

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend  # PHP backend folder
    env:
      DB_HOST: db
      DB_NAME: reactsecure
      DB_USER: reactuser
      DB_PASS: StrongPass123!
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: reactsecure
          MYSQL_USER: reactuser
          MYSQL_PASSWORD: StrongPass123!
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo_mysql

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            dockerize -wait tcp://localhost:3306 -timeout 1s && break || \
            echo "Waiting for MySQL… ($i)" && sleep 2
          done

      - name: Start PHP built-in server
        run: php -S 127.0.0.1:8000 -t .

      - name: Wait for PHP server
        run: |
          for i in {1..20}; do
            curl --silent --fail http://127.0.0.1:8000/register.php && break
            echo "Waiting for PHP… ($i)" && sleep 1
          done

      - name: Run backend tests
        run: bash test-backend.sh
