   backend:
     runs-on: ubuntu-latest
     defaults:
       run:
         working-directory: ./backend
     services:
@@
     steps:
       - uses: actions/checkout@v3

+      # DEBUG: show backend folder contents
+      - name: List backend directory
+        run: ls -R .

       - name: Wait for MySQL
         run: |
           for i in {1..10}; do
             mysqladmin ping -h127.0.0.1 -uroot -prootpassword --silent && break
             echo "Waiting for MySQL… ($i)"
             sleep 2
           done

       - name: Run backend tests
         run: bash test-backend.sh
