name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .    # React app at repo root
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run front-end tests
        run: npm test

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend  # PHP backend folder
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: reactsecure
          MYSQL_USER: reactuser
          MYSQL_PASSWORD: StrongPass123!
        # no ports needed—actions will network it in
    steps:
      - uses: actions/checkout@v3

      - name: Install MySQL client
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update
          apt-get install -y default-mysql-client

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            mysql -hmysql -uroot -prootpassword -e "SELECT 1" && break
            echo "Waiting for MySQL… ($i)"
            sleep 2
          done

      - name: List backend directory
        run: ls -R .

      - name: Run backend tests
        run: bash test-backend.sh
