name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .    # React app at repo root
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run front-end tests
        run: npm test

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend  # switch into your backend folder
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: reactsecure
          MYSQL_USER: reactuser
          MYSQL_PASSWORD: StrongPass123!
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo_mysql

      - name: Start PHP built-in server
        # serve the backend directory on port 8000 in the background
        run: php -S 127.0.0.1:8000 -t . &
      
      - name: Wait for PHP server to be ready
        run: |
          for i in {1..20}; do
            curl --silent --fail http://127.0.0.1:8000/register.php && break
            echo "Waiting for PHP server… ($i)"
            sleep 2
          done

      - name: Run backend tests
        # now that both MySQL service and PHP server are up, run your test script
        run: bash test-backend.sh
